kreyu_data_table:
    defaults:
        exporting:
            enabled: true
        themes:
            - 'themes/data_table_bootstrap_5.html.twig'
            - '@KreyuDataTable/themes/bootstrap_icons_webfont.html.twig'
