framework:
    default_locale: '%env(string:APP_DEFAULT_LOCALE)%'
    enabled_locales: ['en', 'pl']
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:
